name: ${name}
description: ${description}
authors:
  - srnyx
website: https://srnyx.com

main: ${mainPackage}.${name}
version: ${version}
api-version: 1.13

commands:
  eereload:
    description: Reloads the config and messages files
    aliases:
      - erraticreload
      - erraticexplosionsreload
    permission: ee.command.reload

permissions:
  ee.command.reload:
    description: Allows the player to use /eereload
